"""
MYTUBE-370: FFmpeg command generation for silent video — audio map options are omitted.

Objective
---------
Verify that the internal runner detects the absence of audio and conditionally
excludes invalid audio mapping arguments from the FFmpeg command.

Steps
-----
1. Initiate a transcoding process using a silent/video-only input file.
2. Capture the FFmpeg command generated by
   ``api/cmd/transcoder/internal/ffmpeg/runner.go``.
3. Verify that the command does NOT include ``-map 0:a:0``, ``-map 0:a``, or
   any ``-c:a`` (audio codec) settings.

Expected Result
---------------
The generated FFmpeg command excludes all audio mapping parameters, ensuring
it is compatible with a video-only source stream.

Implementation notes
--------------------
This test delegates to the existing Go unit tests in
``api/cmd/transcoder/internal/ffmpeg/runner_test.go`` that were implemented
as part of the same feature.  A Python subprocess wrapper is used so the test
can be discovered and executed by the shared pytest infrastructure.

No environment variables or external services are required — the Go tests use
stub runners that simulate audio-stream detection without calling a real
FFmpeg binary.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path
from typing import NamedTuple

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[3]   # …/mytube/mytube
_API_DIR   = _REPO_ROOT / "api"

# Go package under test.
_FFMPEG_PKG = "./cmd/transcoder/internal/ffmpeg/..."

# Individual Go test function names that cover the MYTUBE-370 acceptance criteria.
_SILENT_VIDEO_TESTS = [
    "TestTranscodeHLS_SilentVideo_NoAudioMapArgs",
    "TestTranscodeHLS_SilentVideo_StreamMapNoAudio",
    "TestTranscodeHLS_SilentVideo_VideoMapArgPresent",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

class GoTestResult(NamedTuple):
    passed: bool
    stdout: str
    returncode: int


def _run_go_tests(run_pattern: str) -> GoTestResult:
    """Execute ``go test`` for the ffmpeg package filtered by *run_pattern*.

    Returns a :class:`GoTestResult` describing whether all tests passed.
    Raises ``FileNotFoundError`` if ``go`` is not on PATH.
    """
    result = subprocess.run(
        ["go", "test", _FFMPEG_PKG, "-v", "-run", run_pattern],
        cwd=str(_API_DIR),
        capture_output=True,
        text=True,
    )
    combined = result.stdout + result.stderr
    return GoTestResult(
        passed=result.returncode == 0,
        stdout=combined,
        returncode=result.returncode,
    )


def _go_available() -> bool:
    try:
        subprocess.run(["go", "version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def _parse_failed_tests(output: str) -> list[str]:
    """Return a list of Go test function names that appear as FAIL in output."""
    return re.findall(r"--- FAIL: (\S+)", output)


def _parse_passed_tests(output: str) -> list[str]:
    """Return a list of Go test function names that appear as PASS in output."""
    return re.findall(r"--- PASS: (\S+)", output)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module", autouse=True)
def require_go():
    """Skip entire module when Go toolchain is not available."""
    if not _go_available():
        pytest.skip(
            "Go toolchain not found on PATH — cannot run MYTUBE-370 Go unit tests."
        )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestFFmpegSilentVideo:
    """MYTUBE-370: Silent video must produce an FFmpeg command without audio maps."""

    # ------------------------------------------------------------------
    # Step 1 + 2 + 3 (primary acceptance criterion)
    # ------------------------------------------------------------------

    def test_silent_video_no_audio_map_args(self) -> None:
        """Step 3a: FFmpeg args must NOT contain '-map 0:a:0' or '-c:a' for silent video.

        Runs Go test ``TestTranscodeHLS_SilentVideo_NoAudioMapArgs`` which:
        - Creates a Runner with a stub ProbeRunner that reports *no* audio stream.
        - Calls TranscodeHLS with the three default renditions.
        - Asserts the generated args string contains neither ``0:a:0`` nor ``-c:a``
          nor ``-b:a``.
        """
        result = _run_go_tests("TestTranscodeHLS_SilentVideo_NoAudioMapArgs")
        assert result.passed, (
            "TestTranscodeHLS_SilentVideo_NoAudioMapArgs FAILED.\n\n"
            f"The FFmpeg command generated for a silent (video-only) input still "
            f"contains audio mapping arguments (-map 0:a:0, -c:a, or -b:a), which "
            f"causes FFmpeg to exit with 'Invalid argument'.\n\n"
            f"Go test output:\n{result.stdout}"
        )

    def test_silent_video_stream_map_no_audio(self) -> None:
        """Step 3b: '-var_stream_map' must NOT reference audio streams for silent video.

        Runs Go test ``TestTranscodeHLS_SilentVideo_StreamMapNoAudio`` which:
        - Checks that the ``-var_stream_map`` value does not contain ``',a:'``
          (audio stream specifiers) when there is no audio stream.
        - Also verifies that video entries (``v:0``, ``v:1``, ``v:2``) are present.
        """
        result = _run_go_tests("TestTranscodeHLS_SilentVideo_StreamMapNoAudio")
        assert result.passed, (
            "TestTranscodeHLS_SilentVideo_StreamMapNoAudio FAILED.\n\n"
            f"The -var_stream_map value for a silent video incorrectly references "
            f"audio streams (e.g. ',a:0'), causing FFmpeg to fail when muxing.\n\n"
            f"Go test output:\n{result.stdout}"
        )

    def test_silent_video_video_map_present(self) -> None:
        """Step 3c: Video stream map '-map 0:v:0' must remain for every rendition.

        Runs Go test ``TestTranscodeHLS_SilentVideo_VideoMapArgPresent`` which:
        - Counts occurrences of ``0:v:0`` in the FFmpeg args.
        - Expects exactly one occurrence per rendition (three for DefaultRenditions).
        """
        result = _run_go_tests("TestTranscodeHLS_SilentVideo_VideoMapArgPresent")
        assert result.passed, (
            "TestTranscodeHLS_SilentVideo_VideoMapArgPresent FAILED.\n\n"
            f"When transcoding a silent video the '-map 0:v:0' argument is missing "
            f"for one or more renditions, so the output HLS stream would have no "
            f"video.\n\n"
            f"Go test output:\n{result.stdout}"
        )

    # ------------------------------------------------------------------
    # Sanity: run all silent-video-related Go tests in a single pass
    # ------------------------------------------------------------------

    def test_all_silent_video_go_tests_pass(self) -> None:
        """End-to-end: all Go tests related to silent-video transcoding must pass.

        This is the integration checkpoint — it runs the full set of
        silent-video tests together and asserts all pass, mirroring exactly what
        a CI pipeline would do.
        """
        pattern = "|".join(_SILENT_VIDEO_TESTS)
        result = _run_go_tests(pattern)

        passed_tests = _parse_passed_tests(result.stdout)
        failed_tests = _parse_failed_tests(result.stdout)

        assert result.passed, (
            f"One or more Go silent-video tests failed.\n\n"
            f"Failed tests: {failed_tests}\n"
            f"Passed tests: {passed_tests}\n\n"
            f"Go test output:\n{result.stdout}"
        )

        # Confirm that at least the three key tests were actually run.
        for expected in _SILENT_VIDEO_TESTS:
            assert expected in passed_tests, (
                f"Expected Go test '{expected}' to run and pass, but it was not "
                f"found in the PASS list.\n"
                f"Passed tests: {passed_tests}\n"
                f"Full output:\n{result.stdout}"
            )
