# infra/cloudjobs.yaml — Cloud Run Job definition for mytube-transcoder.
#
# This file documents the desired Cloud Run Job configuration.
# It is applied via the setup.sh gcloud commands; update it when the
# actual transcoder image becomes available (FFmpeg story).
#
# Reference:
#   https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.jobs
#
# Equivalent gcloud command (executed by setup.sh):
#
#   gcloud run jobs create mytube-transcoder \
#     --image gcr.io/${GCP_PROJECT_ID}/mytube-transcoder:latest \
#     --region ${GCP_REGION} \
#     --service-account mytube-transcoder@${GCP_PROJECT_ID}.iam.gserviceaccount.com \
#     --set-env-vars HLS_BUCKET=mytube-hls-output \
#     --max-retries 1 \
#     --task-timeout 3600 \
#     --project ${GCP_PROJECT_ID}

apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: mytube-transcoder
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: mytube-transcoder  # short name; full email resolved by GCP
          maxRetries: 1
          timeoutSeconds: "3600"
          containers:
            - image: gcr.io/${GCP_PROJECT_ID}/mytube-transcoder:latest
              # Per-execution overrides are injected by the trigger service at
              # runtime via the Cloud Run Jobs API "overrides" field.
              # Static env vars that never change between executions live here.
              env:
                - name: HLS_BUCKET
                  value: mytube-hls-output
              resources:
                limits:
                  cpu: "2"
                  memory: 2Gi
